### ISSUE TITLE
Classloader Question

### ISSUE THREAD

**Issue by OCram85** [RamblingCookieMonster/WritingModules#1]
Hi CookieMonster,

I've recently watched your [presentation](https://youtu.be/J3ZUS4t6jrE) from the PowerShell Summit 2017.

You mentioned it wouldn't be a great idea to use the `ScriptsToProcess` for loading classes from modules into the parent scope. Unfortunately there isn't any goo documentation or best practice therefore and I [couldn't find any better solution](http://stackoverflow.com/questions/41037575/how-to-export-classes-from-modules-when-the-class-definition-is-dotsourced).

So how did you solved this problem? It would be great to get some advice from such a pro like you ;)

_If you are interested in the exact problem your can take a look at my repo called [Ponduit](/OCram85/Ponduit)._

**Comment by RamblingCookieMonster** [comment]
Hi!

I've seen a good number of folks either:

* Include all necessary classes in the psm1
* Keep classes in separate files, during build process, concatenate them into psm1 as needed (e.g.[ PoshBot](https://github.com/poshbotio/PoshBot))

Might be other options as well - if you drop by the PowerShell Slack team (invite @ slack.poshcode.org), you can ping folks like Jaykul and others who are more involved in writing modules that use classes

Cheers!

**Comment by RamblingCookieMonster** [comment]
Closing this out - if you end up using any interesting approaches feel free to reply with them - cheers!
